package com.forge.vdesign.domain.model

/**
 * Domain model for a single chat message.
 * Kept minimal — maps 1-to-1 with what the UI and ViewModel need.
 * Persistence mapping is handled in the data layer (MessageEntity).
 */
data class ChatMessage(
    val id: String,
    val conversationId: String,
    val role: MessageRole,
    val content: String,
    val timestamp: Long = System.currentTimeMillis(),
    val tokenCount: Int = 0,
    val designReasoning: List<DesignDecision> = emptyList(),
    val isLoading: Boolean = false,
    val isCanvasCard: Boolean = false,
    val canvasPrompt: String = "",
    /** Real DesignBrief deserialized from Room metadata — null for non-canvas messages */
    val embeddedBrief: DesignBrief? = null,
    val isAgentActivity: Boolean = false,
    val agentTasks: List<AgentTask> = emptyList(),
    /** Screen result card — generated by the agent and shown inline in chat */
    val isScreenCard: Boolean = false,
    val screenshotUrl: String? = null,
    val htmlUrl: String? = null,
    val screenCardProjectId: String? = null
)

enum class MessageRole(val apiValue: String) {
    USER("user"),
    ASSISTANT("assistant"),
    SYSTEM("system");

    companion object {
        fun fromApiValue(value: String): MessageRole =
            entries.firstOrNull { it.apiValue == value } ?: ASSISTANT
    }
}

/**
 * A single step in the FORGE agent task log
 * Rendered as a distinct line in the Agent Activity card.
 */
enum class TaskStatus { PENDING, ACTIVE, DONE, ERROR }

data class AgentTask(
    val label: String,
    val status: TaskStatus = TaskStatus.PENDING,
    val detail: String? = null
) {
    val icon: String get() = when (status) {
        TaskStatus.DONE    -> "✓"
        TaskStatus.ACTIVE  -> "⟳"
        TaskStatus.ERROR   -> "✗"
        TaskStatus.PENDING -> "·"
    }
    val formatted: String get() = if (detail != null) "$icon $label \u2014 $detail" else "$icon $label"
}

/**
 * A single design decision the Brain made when generating a screen.
 * Displayed in the Design Reasoning UI panel below the canvas.
 */
data class DesignDecision(
    val decision: String,       // What the agent decided
    val principle: String,      // The design principle it applied
    val sourceBook: String,     // The canonical book it came from
    val skillId: String,        // e.g. "visual-hierarchy"
)
